using System.Collections.Generic;

namespace ACME.PRJ.CodebaseCommons
{
	/// <summary>
	/// Базовый класс для типов с метаданными об элементах source-кода
	/// </summary>
	public abstract class InfoBase
	{
		public int Id { get; set; }

		public string Key { get; set; }

		public string Name { get; set; }

		/// <summary>
		/// Autogenerated
		/// </summary>
		public override bool Equals(object obj)
		{
			var @base = obj as InfoBase;
			return @base != null &&
				   Key == @base.Key &&
				   Name == @base.Name &&
				   Id == @base.Id;
		}

		/// <summary>
		/// Autogenerated
		/// </summary>
		public override int GetHashCode()
		{
			var hashCode = 821586674;
			hashCode = hashCode * -1521134295 + Id.GetHashCode();
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Key);
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Name);
			return hashCode;
		}

		public override string ToString()
		{
			return $"#{Id} : {Key}  '{Name}'"; // для отладки
		}

		public virtual bool IsValid()
		{
			return !string.IsNullOrEmpty(Key);
		}
	}
}
