using System.Collections.Generic;

namespace ACME.PRJ.CodebaseCommons
{
	/// <summary>
	/// Инфо о файле/каталоге
	/// </summary>
	public class SourceItemInfo : InfoBase
	{
		public string FolderPath { get; set; }

		public string Extension { get; set; }

		public string ContentId { get; set; }

		public string Node { get; set; }

		public SourceItemTypes Type { get; set; }

		public int Size { get; set; }

		//public string Parent { get; set; } // нужен ли?

		public BranchInfo Branch { get; set; }

		public string FullPath
		{
			get => Key;
			set => Key = value;
		}
		
		/// <summary>
		/// Autogenerated
		/// </summary>
		public override bool Equals(object obj)
		{
			var info = obj as SourceItemInfo;
			return info != null &&
				   base.Equals(obj) &&
				   FolderPath == info.FolderPath &&
				   Extension == info.Extension &&
				   Type == info.Type &&
				   Size == info.Size &&
				   Branch.Equals(info.Branch);
		}
		
		/// <summary>
		/// Autogenerated
		/// </summary>
		public override int GetHashCode()
		{
			var hashCode = 1968611531;
			hashCode = hashCode * -1521134295 + base.GetHashCode();
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(FolderPath);
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Extension);
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(ContentId);
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Node);
			hashCode = hashCode * -1521134295 + Type.GetHashCode();
			hashCode = hashCode * -1521134295 + Size.GetHashCode();
			hashCode = hashCode * -1521134295 + EqualityComparer<BranchInfo>.Default.GetHashCode(Branch);
			hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(FullPath);
			return hashCode;
		}

		public override bool IsValid()
		{
			return Type != default
				&& Size >= Constants.UnknownSize
				&& (Branch?.IsValid() == true)
				&& base.IsValid();
		}
	}

	public enum SourceItemTypes
	{
		Unknown = 0,
		File = 1,
		Directory = 2
	}
}
